services:
  server:
    image: ${PROJECT_NAME}-app
    container_name: ${PROJECT_NAME}-server
    user: ${CURRENT_UID}:${CURRENT_GID}
    working_dir: /app
    volumes:
      - ../:/app
    environment:
      - GRPC_ADDRESS=:${GRPC_SRV_PORT}
      - DATABASE_URI=${DATABASE_URI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${GRPC_LOCAL_PORT}:${GRPC_SRV_PORT}"
    command: /app/bin/server/server
    networks:
      - goph_keeper
  db:
    image: postgres:latest
    container_name: ${PROJECT_NAME}-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goph_keeper
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5428:5432"
    volumes:
      - /tmp/goph_pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - goph_keeper
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
networks:
  goph_keeper:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.24.0.0/16