// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: contracts/user_data.v1.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDataItem_DataType int32

const (
	UserDataItem_TEXT   UserDataItem_DataType = 0
	UserDataItem_BINARY UserDataItem_DataType = 1
	UserDataItem_CARD   UserDataItem_DataType = 2
)

// Enum value maps for UserDataItem_DataType.
var (
	UserDataItem_DataType_name = map[int32]string{
		0: "TEXT",
		1: "BINARY",
		2: "CARD",
	}
	UserDataItem_DataType_value = map[string]int32{
		"TEXT":   0,
		"BINARY": 1,
		"CARD":   2,
	}
)

func (x UserDataItem_DataType) Enum() *UserDataItem_DataType {
	p := new(UserDataItem_DataType)
	*p = x
	return p
}

func (x UserDataItem_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserDataItem_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_user_data_v1_proto_enumTypes[0].Descriptor()
}

func (UserDataItem_DataType) Type() protoreflect.EnumType {
	return &file_contracts_user_data_v1_proto_enumTypes[0]
}

func (x UserDataItem_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserDataItem_DataType.Descriptor instead.
func (UserDataItem_DataType) EnumDescriptor() ([]byte, []int) {
	return file_contracts_user_data_v1_proto_rawDescGZIP(), []int{1, 0}
}

type MetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	mi := &file_contracts_user_data_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_data_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_contracts_user_data_v1_proto_rawDescGZIP(), []int{0}
}

func (x *MetaData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MetaData) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UserDataItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type          UserDataItem_DataType  `protobuf:"varint,3,opt,name=type,proto3,enum=user.data.v1.UserDataItem_DataType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      []*MetaData            `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDataItem) Reset() {
	*x = UserDataItem{}
	mi := &file_contracts_user_data_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataItem) ProtoMessage() {}

func (x *UserDataItem) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_data_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataItem.ProtoReflect.Descriptor instead.
func (*UserDataItem) Descriptor() ([]byte, []int) {
	return file_contracts_user_data_v1_proto_rawDescGZIP(), []int{1}
}

func (x *UserDataItem) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UserDataItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UserDataItem) GetType() UserDataItem_DataType {
	if x != nil {
		return x.Type
	}
	return UserDataItem_TEXT
}

func (x *UserDataItem) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UserDataItem) GetMetadata() []*MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserDataItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserDataItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateUserDataItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *UserDataItem          `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserDataItemRequest) Reset() {
	*x = CreateUserDataItemRequest{}
	mi := &file_contracts_user_data_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserDataItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserDataItemRequest) ProtoMessage() {}

func (x *CreateUserDataItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_data_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserDataItemRequest.ProtoReflect.Descriptor instead.
func (*CreateUserDataItemRequest) Descriptor() ([]byte, []int) {
	return file_contracts_user_data_v1_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserDataItemRequest) GetItem() *UserDataItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateUserDataItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *UserDataItem          `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserDataItemResponse) Reset() {
	*x = CreateUserDataItemResponse{}
	mi := &file_contracts_user_data_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserDataItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserDataItemResponse) ProtoMessage() {}

func (x *CreateUserDataItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_data_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserDataItemResponse.ProtoReflect.Descriptor instead.
func (*CreateUserDataItemResponse) Descriptor() ([]byte, []int) {
	return file_contracts_user_data_v1_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserDataItemResponse) GetItem() *UserDataItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateUserDataItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *UserDataItem          `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserDataItemRequest) Reset() {
	*x = UpdateUserDataItemRequest{}
	mi := &file_contracts_user_data_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserDataItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserDataItemRequest) ProtoMessage() {}

func (x *UpdateUserDataItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_data_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserDataItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserDataItemRequest) Descriptor() ([]byte, []int) {
	return file_contracts_user_data_v1_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserDataItemRequest) GetItem() *UserDataItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateUserDataItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *UserDataItem          `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserDataItemResponse) Reset() {
	*x = UpdateUserDataItemResponse{}
	mi := &file_contracts_user_data_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserDataItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserDataItemResponse) ProtoMessage() {}

func (x *UpdateUserDataItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_data_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserDataItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserDataItemResponse) Descriptor() ([]byte, []int) {
	return file_contracts_user_data_v1_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserDataItemResponse) GetItem() *UserDataItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetUserDataItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemUuid      string                 `protobuf:"bytes,1,opt,name=item_uuid,json=itemUuid,proto3" json:"item_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataItemRequest) Reset() {
	*x = GetUserDataItemRequest{}
	mi := &file_contracts_user_data_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataItemRequest) ProtoMessage() {}

func (x *GetUserDataItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_data_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataItemRequest.ProtoReflect.Descriptor instead.
func (*GetUserDataItemRequest) Descriptor() ([]byte, []int) {
	return file_contracts_user_data_v1_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserDataItemRequest) GetItemUuid() string {
	if x != nil {
		return x.ItemUuid
	}
	return ""
}

type GetUserDataItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *UserDataItem          `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataItemResponse) Reset() {
	*x = GetUserDataItemResponse{}
	mi := &file_contracts_user_data_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataItemResponse) ProtoMessage() {}

func (x *GetUserDataItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_data_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataItemResponse.ProtoReflect.Descriptor instead.
func (*GetUserDataItemResponse) Descriptor() ([]byte, []int) {
	return file_contracts_user_data_v1_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserDataItemResponse) GetItem() *UserDataItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetUserDataItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemUuids     []string               `protobuf:"bytes,1,rep,name=item_uuids,json=itemUuids,proto3" json:"item_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataItemsRequest) Reset() {
	*x = GetUserDataItemsRequest{}
	mi := &file_contracts_user_data_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataItemsRequest) ProtoMessage() {}

func (x *GetUserDataItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_data_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataItemsRequest.ProtoReflect.Descriptor instead.
func (*GetUserDataItemsRequest) Descriptor() ([]byte, []int) {
	return file_contracts_user_data_v1_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserDataItemsRequest) GetItemUuids() []string {
	if x != nil {
		return x.ItemUuids
	}
	return nil
}

type GetUserDataItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserDataItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataItemsResponse) Reset() {
	*x = GetUserDataItemsResponse{}
	mi := &file_contracts_user_data_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataItemsResponse) ProtoMessage() {}

func (x *GetUserDataItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_data_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataItemsResponse.ProtoReflect.Descriptor instead.
func (*GetUserDataItemsResponse) Descriptor() ([]byte, []int) {
	return file_contracts_user_data_v1_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserDataItemsResponse) GetItems() []*UserDataItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteUserDataItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemUuids     []string               `protobuf:"bytes,1,rep,name=item_uuids,json=itemUuids,proto3" json:"item_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserDataItemsRequest) Reset() {
	*x = DeleteUserDataItemsRequest{}
	mi := &file_contracts_user_data_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserDataItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserDataItemsRequest) ProtoMessage() {}

func (x *DeleteUserDataItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_data_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserDataItemsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserDataItemsRequest) Descriptor() ([]byte, []int) {
	return file_contracts_user_data_v1_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteUserDataItemsRequest) GetItemUuids() []string {
	if x != nil {
		return x.ItemUuids
	}
	return nil
}

var File_contracts_user_data_v1_proto protoreflect.FileDescriptor

const file_contracts_user_data_v1_proto_rawDesc = "" +
	"\n" +
	"\x1ccontracts/user_data.v1.proto\x12\fuser.data.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n" +
	"\bMetaData\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xdb\x02\n" +
	"\fUserDataItem\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x127\n" +
	"\x04type\x18\x03 \x01(\x0e2#.user.data.v1.UserDataItem.DataTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x122\n" +
	"\bmetadata\x18\x05 \x03(\v2\x16.user.data.v1.MetaDataR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"*\n" +
	"\bDataType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\n" +
	"\n" +
	"\x06BINARY\x10\x01\x12\b\n" +
	"\x04CARD\x10\x02\"K\n" +
	"\x19CreateUserDataItemRequest\x12.\n" +
	"\x04item\x18\x01 \x01(\v2\x1a.user.data.v1.UserDataItemR\x04item\"L\n" +
	"\x1aCreateUserDataItemResponse\x12.\n" +
	"\x04item\x18\x01 \x01(\v2\x1a.user.data.v1.UserDataItemR\x04item\"K\n" +
	"\x19UpdateUserDataItemRequest\x12.\n" +
	"\x04item\x18\x01 \x01(\v2\x1a.user.data.v1.UserDataItemR\x04item\"L\n" +
	"\x1aUpdateUserDataItemResponse\x12.\n" +
	"\x04item\x18\x01 \x01(\v2\x1a.user.data.v1.UserDataItemR\x04item\"5\n" +
	"\x16GetUserDataItemRequest\x12\x1b\n" +
	"\titem_uuid\x18\x01 \x01(\tR\bitemUuid\"I\n" +
	"\x17GetUserDataItemResponse\x12.\n" +
	"\x04item\x18\x01 \x01(\v2\x1a.user.data.v1.UserDataItemR\x04item\"8\n" +
	"\x17GetUserDataItemsRequest\x12\x1d\n" +
	"\n" +
	"item_uuids\x18\x01 \x03(\tR\titemUuids\"L\n" +
	"\x18GetUserDataItemsResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.user.data.v1.UserDataItemR\x05items\";\n" +
	"\x1aDeleteUserDataItemsRequest\x12\x1d\n" +
	"\n" +
	"item_uuids\x18\x01 \x03(\tR\titemUuids2\xff\x03\n" +
	"\x0fUserDataService\x12g\n" +
	"\x12CreateUserDataItem\x12'.user.data.v1.CreateUserDataItemRequest\x1a(.user.data.v1.CreateUserDataItemResponse\x12g\n" +
	"\x12UpdateUserDataItem\x12'.user.data.v1.UpdateUserDataItemRequest\x1a(.user.data.v1.UpdateUserDataItemResponse\x12^\n" +
	"\x0fGetUserDataItem\x12$.user.data.v1.GetUserDataItemRequest\x1a%.user.data.v1.GetUserDataItemResponse\x12a\n" +
	"\x10GetUserDataItems\x12%.user.data.v1.GetUserDataItemsRequest\x1a&.user.data.v1.GetUserDataItemsResponse\x12W\n" +
	"\x13DeleteUserDataItems\x12(.user.data.v1.DeleteUserDataItemsRequest\x1a\x16.google.protobuf.EmptyB\x1cZ\x1ainternal/contracts/v1/datab\x06proto3"

var (
	file_contracts_user_data_v1_proto_rawDescOnce sync.Once
	file_contracts_user_data_v1_proto_rawDescData []byte
)

func file_contracts_user_data_v1_proto_rawDescGZIP() []byte {
	file_contracts_user_data_v1_proto_rawDescOnce.Do(func() {
		file_contracts_user_data_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_user_data_v1_proto_rawDesc), len(file_contracts_user_data_v1_proto_rawDesc)))
	})
	return file_contracts_user_data_v1_proto_rawDescData
}

var file_contracts_user_data_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contracts_user_data_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_contracts_user_data_v1_proto_goTypes = []any{
	(UserDataItem_DataType)(0),         // 0: user.data.v1.UserDataItem.DataType
	(*MetaData)(nil),                   // 1: user.data.v1.MetaData
	(*UserDataItem)(nil),               // 2: user.data.v1.UserDataItem
	(*CreateUserDataItemRequest)(nil),  // 3: user.data.v1.CreateUserDataItemRequest
	(*CreateUserDataItemResponse)(nil), // 4: user.data.v1.CreateUserDataItemResponse
	(*UpdateUserDataItemRequest)(nil),  // 5: user.data.v1.UpdateUserDataItemRequest
	(*UpdateUserDataItemResponse)(nil), // 6: user.data.v1.UpdateUserDataItemResponse
	(*GetUserDataItemRequest)(nil),     // 7: user.data.v1.GetUserDataItemRequest
	(*GetUserDataItemResponse)(nil),    // 8: user.data.v1.GetUserDataItemResponse
	(*GetUserDataItemsRequest)(nil),    // 9: user.data.v1.GetUserDataItemsRequest
	(*GetUserDataItemsResponse)(nil),   // 10: user.data.v1.GetUserDataItemsResponse
	(*DeleteUserDataItemsRequest)(nil), // 11: user.data.v1.DeleteUserDataItemsRequest
	(*timestamppb.Timestamp)(nil),      // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 13: google.protobuf.Empty
}
var file_contracts_user_data_v1_proto_depIdxs = []int32{
	0,  // 0: user.data.v1.UserDataItem.type:type_name -> user.data.v1.UserDataItem.DataType
	1,  // 1: user.data.v1.UserDataItem.metadata:type_name -> user.data.v1.MetaData
	12, // 2: user.data.v1.UserDataItem.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: user.data.v1.UserDataItem.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 4: user.data.v1.CreateUserDataItemRequest.item:type_name -> user.data.v1.UserDataItem
	2,  // 5: user.data.v1.CreateUserDataItemResponse.item:type_name -> user.data.v1.UserDataItem
	2,  // 6: user.data.v1.UpdateUserDataItemRequest.item:type_name -> user.data.v1.UserDataItem
	2,  // 7: user.data.v1.UpdateUserDataItemResponse.item:type_name -> user.data.v1.UserDataItem
	2,  // 8: user.data.v1.GetUserDataItemResponse.item:type_name -> user.data.v1.UserDataItem
	2,  // 9: user.data.v1.GetUserDataItemsResponse.items:type_name -> user.data.v1.UserDataItem
	3,  // 10: user.data.v1.UserDataService.CreateUserDataItem:input_type -> user.data.v1.CreateUserDataItemRequest
	5,  // 11: user.data.v1.UserDataService.UpdateUserDataItem:input_type -> user.data.v1.UpdateUserDataItemRequest
	7,  // 12: user.data.v1.UserDataService.GetUserDataItem:input_type -> user.data.v1.GetUserDataItemRequest
	9,  // 13: user.data.v1.UserDataService.GetUserDataItems:input_type -> user.data.v1.GetUserDataItemsRequest
	11, // 14: user.data.v1.UserDataService.DeleteUserDataItems:input_type -> user.data.v1.DeleteUserDataItemsRequest
	4,  // 15: user.data.v1.UserDataService.CreateUserDataItem:output_type -> user.data.v1.CreateUserDataItemResponse
	6,  // 16: user.data.v1.UserDataService.UpdateUserDataItem:output_type -> user.data.v1.UpdateUserDataItemResponse
	8,  // 17: user.data.v1.UserDataService.GetUserDataItem:output_type -> user.data.v1.GetUserDataItemResponse
	10, // 18: user.data.v1.UserDataService.GetUserDataItems:output_type -> user.data.v1.GetUserDataItemsResponse
	13, // 19: user.data.v1.UserDataService.DeleteUserDataItems:output_type -> google.protobuf.Empty
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_contracts_user_data_v1_proto_init() }
func file_contracts_user_data_v1_proto_init() {
	if File_contracts_user_data_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_user_data_v1_proto_rawDesc), len(file_contracts_user_data_v1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_user_data_v1_proto_goTypes,
		DependencyIndexes: file_contracts_user_data_v1_proto_depIdxs,
		EnumInfos:         file_contracts_user_data_v1_proto_enumTypes,
		MessageInfos:      file_contracts_user_data_v1_proto_msgTypes,
	}.Build()
	File_contracts_user_data_v1_proto = out.File
	file_contracts_user_data_v1_proto_goTypes = nil
	file_contracts_user_data_v1_proto_depIdxs = nil
}
