name: unit tests

on: [pull_request]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Setup Go
         uses: actions/setup-go@v5
         with:
           go-version: "^1.25"
           cache: true

       - name: Run unit tests
         run: |
           go test ./...
